In [2]:
import os
import torch
import torch.nn as nn
import torch.nn.functional as nfunc


os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ['CUDA_VISIBLE_DEVICES'] = "3"

no_cuda = False
cuda = not no_cuda and torch.cuda.is_available()
device = torch.device("cuda" if cuda else "cpu")

# Advanced index by torch.gather





    torch.gather(input, dim, index, out=None) ? Tensor

        Gathers values along an axis specified by dim.

        For a 3-D tensor the output is specified by:

        out[i][j][k] = input[index[i][j][k]][j][k]  # dim=0
        out[i][j][k] = input[i][index[i][j][k]][k]  # dim=1
        out[i][j][k] = input[i][j][index[i][j][k]]  # dim=2

        Parameters: 

            input (Tensor) ? The source tensor
            dim (int) ? The axis along which to index
            index (LongTensor) ? The indices of elements to gather
            out (Tensor, optional) ? Destination tensor

        Example:

        >>> t = torch.Tensor([[1,2],[3,4]])
        >>> torch.gather(t, 1, torch.LongTensor([[0,0],[1,0]]))
         1  1
         4  3
        [torch.FloatTensor of size 2x2]



In [1]:
import torch
import torch.nn.functional as nfunc

In [2]:
p = torch.rand((10, 10))

# random initialization by GPU

In [4]:
x = torch.rand((1, 2, 3), device=device)

In [11]:
l = torch.randperm(100, device=device)
l

tensor([84, 33, 44, 58,  7,  6, 52, 73, 72, 51, 31, 15, 50, 32, 78, 46, 24, 81,
        19, 91, 36, 18, 21, 70, 49, 55, 14, 42, 40, 79,  0, 96, 62, 92, 30, 41,
        85, 65, 13, 28, 74, 90, 69, 17, 56, 68, 45, 87,  8, 89, 77, 25,  3, 35,
        94,  4, 82,  5, 71, 43, 23, 12, 86, 29, 66, 60, 80, 48, 26, 37, 27,  1,
        54, 57, 99, 34, 83, 93, 22, 20, 98,  9, 67, 95, 75, 11,  2, 61, 10, 63,
        39, 97, 38, 76, 16, 53, 47, 88, 64, 59], device='cuda:0')

In [15]:
torch.randint(0, 100, size=(1, ))

tensor([31])

In [10]:
t = torch.arange(1000, dtype=torch.int, device=device)

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1